#!/bin/sh

PREREQ="udev"

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

[ "$IP" != off -a "$IP" != none -a -x /sbin/sshd ] || exit 0

run_openssh() {
    # always run configure_networking() before openssh; on NFS
    # mounts this has been done already
    [ "$boot" = nfs ] || configure_networking

    if [ -n "$SSH_PORT" ]; then
        SSH_PORT_ARGS="-p $SSH_PORT"
    fi

    # create privilege separation directory
    mkdir -p /run/sshd

    log_begin_msg "Starting OpenSSH on port $SSH_PORT"
    # using exec and keeping openssh in the foreground enables the init-bottom
    # script to kill the remaining ipconfig processes if someone unlocks the
    # rootfs from the console while the network is being configured
    exec /sbin/sshd -D $SSH_PORT_ARGS $SSH_OPTIONS
}

if [ -e /etc/openssh-initramfs/config ]; then
    . /etc/openssh-initramfs/config
fi
. /scripts/functions

# On NFS mounts, wait until the network is configured.  On local mounts,
# configure the network in the background (in run_openssh()) so someone
# with console access can enter the passphrase immediately.  (With the
# default ip=dhcp, configure_networking hangs for 5mins or so when the
# network is unavailable, for instance.)
[ "$boot" != nfs ] || configure_networking

run_openssh &
echo $! >/run/sshd.pid
